TOKEN = 'token'  # Bot token from @BotFather
DATABASE_URL = 'mongodb://username:password@localhost:27017'  # Link DataBase
DATABASE_FSM_NAME = 'anime_girl'  # Name DataBase and Domain for i18n
DATABASE_USERNAME_FSM = 'username'  # login DataBase
DATABASE_PASSWORD_FSM = 'password'  # Password DataBase
DATABASE_HOST_FSM = 'localhost'  # Host DataBase
DATABASE_PORT_FSM = 27017  # Port DataBase
ADMIN_CHAT_ID = 000000000  # Admin id
rate = 1.5  # protect is spam
prefixes = '!/'  # prefixes
